;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-char
        evil-beginning-of-line
        evil-delete-backward-char
        evil-delete-backward-char-and-join
        evil-exit-visual-state
        evil-find-char-to-backward
        evil-forward-char
        evil-forward-word-end
        evil-jump-forward
        evil-next-line
        evil-paste-after
        evil-previous-line
        hydra-mc-forward/body
        hydra-mc-forward/er/contract-region
        hydra-mc-forward/er/expand-region
        hydra-mc-forward/mc/edit-beginnings-of-lines-and-exit
        indent-for-tab-command
        upcase-region
        ))

(setq mc/cmds-to-run-once
      '(
        evil-ex
        evil-force-normal-state
        evil-goto-line
        evil-insert
        evil-mouse-drag-region
        evil-normal-state
        evil-record-macro
        evil-visual-char
        hydra-mc-forward/mc/edit-ends-of-lines-and-exit
        hydra-mc-forward/mc/edit-lines
        hydra-mc-forward/mc/keyboard-quit-and-exit
        hydra-mc-forward/mc/mark-all-like-this-and-exit
        hydra-mc-forward/mc/mark-next-like-this
        hydra-mc-forward/mc/mark-next-like-this-word
        hydra-mc-forward/mc/mark-previous-like-this
        hydra-mc-forward/mc/mark-previous-like-this-word
        hydra-mc-forward/mc/unmark-next-like-this
        hydra-mc-forward/mc/unmark-previous-like-this
        hydra-mc-forward/mc/unmark-previous-like-this-and-exit
        ivy-switch-buffer
        projectile-find-file
        winum-select-window-2
        yaml-electric-backspace
        ))
