;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-once
      '(
        evil-backward-paragraph
        evil-backward-sentence-begin
        evil-ex
        evil-force-normal-state
        evil-goto-line
        evil-insert
        evil-mouse-drag-region
        evil-normal-state
        evil-record-macro
        evil-visual-char
        evil-yank
        hydra-mc-forward/mc/edit-ends-of-lines-and-exit
        hydra-mc-forward/mc/edit-lines
        hydra-mc-forward/mc/keyboard-quit-and-exit
        hydra-mc-forward/mc/mark-all-like-this
        hydra-mc-forward/mc/mark-all-like-this-and-exit
        hydra-mc-forward/mc/mark-next-like-this
        hydra-mc-forward/mc/mark-next-like-this-word
        hydra-mc-forward/mc/mark-previous-like-this
        hydra-mc-forward/mc/mark-previous-like-this-word
        hydra-mc-forward/mc/unmark-next-like-this
        hydra-mc-forward/mc/unmark-previous-like-this
        hydra-mc-forward/mc/unmark-previous-like-this-and-exit
        ivy-switch-buffer
        projectile-find-file
        winum-select-window-2
        winum-select-window-9
        yaml-electric-backspace
        ))
