;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-jump-forward
        evil-next-line
        evil-previous-line
        indent-for-tab-command
        ))

(setq mc/cmds-to-run-once
      '(
        evil-force-normal-state
        evil-normal-state
        ))
