(use-package haskell-mode)
(setq haskell-interactive-popup-errors nil)
;; (use-package intero)
;; (add-hook 'haskell-mode-hook 'intero-mode)
;; (require 'flycheck)
;; (setq flycheck-check-syntax-automatically '(save new-line))
;; (flycheck-add-next-checker 'intero '(warning . haskell-hlint))
